[package]
name = "raccoon-service-sync"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
grpc = [
    "dep:opentelemetry",
    "dep:prost",
    "dep:protoc-bin-vendored",
    "dep:tonic",
    "dep:tonic-prost",
    "dep:tonic-prost-build",
    "dep:tracing-opentelemetry",
]

[dependencies]
async-trait = "0.1.89"
dicom-core = "0.9.1"
dicom-dictionary-std = "0.9.0"
dicom-json = "0.9.0"
dicom-object = "0.9.1"
futures-util = "0.3.31"
opentelemetry = { workspace = true, optional = true }
prost = { version = "0.14.3", optional = true }
raccoon-contract-dicom = { path = "../contract-dicom" }
raccoon-contract-object-store = { path = "../contract-object-store" }
raccoon-service-ingest = { path = "../service-ingest" }
serde_json = "1.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["macros", "rt", "time"] }
tokio-util = "0.7.17"
tonic = { version = "0.14.6", optional = true }
tonic-prost = { version = "0.14.6", optional = true }
tracing.workspace = true
tracing-opentelemetry = { version = "0.32.1", optional = true }

[build-dependencies]
protoc-bin-vendored = { version = "3.2.0", optional = true }
tonic-prost-build = { version = "=0.14.6", optional = true }

[dev-dependencies]
tempfile = "3.23.0"
tokio = { version = "1.52.3", features = ["macros", "rt", "time"] }
